### ISSUE TITLE
Invariant Violation Issue

### ISSUE THREAD

**Issue by NidheeshVenugopal** [Finicity/connect-react-native-sdk#3] opened 2021-05-05 05:45 UTC
connect-react-native-sdk throwing an issue while suing this module. We have followed exactly the same procedure as mentioned in the document  

More details

Usage 

<FinicityConnect
connectUrl={'my url'}
eventHandlers={eventHandlers}
linkingUri={'#UNIVERSAL_LINK#'}
>

error:-

Invariant Violation: View config getter callback for component RCTModalHostView must be a function (received undefined)

Looking for a solution

**Comment by alexsalido** [comment] 2021-09-15 18:58
Duplicate of https://github.com/Finicity/connect-react-native-sdk/issues/2

**Closed by alexsalido** 2021-09-15 18:58 UTC
